//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class PickUpPoint
    {
        public PickUpPoint()
        {
            this.Order = new HashSet<Order>();
        }
    
        public int id { get; set; }
        public Nullable<int> PostCode { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<int> House { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
    }
}
