//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductInOrder
    {
        public int id { get; set; }
        public Nullable<int> number { get; set; }
        public Nullable<int> articleID { get; set; }
        public Nullable<int> Amount { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
