//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoExample
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductInOrder = new HashSet<ProductInOrder>();
        }
    
        public int id { get; set; }
        public string article { get; set; }
        public string Name { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<int> ProducerId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> DIscount { get; set; }
        public Nullable<int> StockQuantity { get; set; }
        public string Description { get; set; }
        public string Photo { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Producer Producer { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual Unit Unit { get; set; }
        public virtual ICollection<ProductInOrder> ProductInOrder { get; set; }
    }
}
